<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoolWSL.App\CoolWSL.App.csproj" />
    <ProjectReference Include="..\CoolWSL.Core\CoolWSL.Core.csproj" />
    <ProjectReference Include="..\CoolWSL.Wsl\CoolWSL.Wsl.csproj" />
    <ProjectReference Include="..\CoolWSL.Configuration\CoolWSL.Configuration.csproj" />
    <ProjectReference Include="..\CoolWSL.Diagnostics\CoolWSL.Diagnostics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.9.3" />
    <PackageReference Include="MSTest.TestFramework" Version="3.9.3" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
  </ItemGroup>
</Project>